language: c

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bison
    - gcc-7
    - g++-7

include:
  os:
    linux

env:
- MRUBY_TARGET=master
- MRUBY_TARGET=1.4.1
- MRUBY_TARGET=1.4.0
- MRUBY_TARGET=1.3.0

script:
- export MRUBY_CONFIG="$TRAVIS_BUILD_DIR/.travis_config.rb"
- MRUBY_URL="https://github.com/mruby/mruby/archive/$MRUBY_TARGET.tar.gz"
- MRUBY_DIR="mruby-$MRUBY_TARGET"
- wget -O- $MRUBY_URL | tar xzf -
- rake -vf $MRUBY_DIR/Rakefile test
